app/ideas/__init__.py
from flask import Blueprint

ideas = Blueprint('ideas', __name__, url_prefix='/ideas', template_folder='templates')

from . import views

app/ideas/views.py
from flask import render_template as render, flash, redirect, url_for
from flask_login import login_required, current_user
from . import ideas
from app.services import get_Category_by_id, delete_category, create_category, list_categories, list_ideas_by_username, create_idea, delete_idea_db, update_state_idea_db, update_idea_db, get_idea_by_id
from .form import DeleteCategoryForm, RegisterCategoryForm, IdeaForm, DeleteIdeaForm, PublicIdeaForm
from app.utils import get_dict_from_wftform

def contextHome():
    username = current_user.id
    categories = [(c["id"], c["name"]) for c in list_categories() ]
    idea_form = IdeaForm()
    idea_form.category_id.choices = [("", "--seleccione categoria --") ] + categories
    context = {
        'username': username,
        'ideas': list_ideas_by_username(username),
        'idea_form': idea_form,
        'delete_form': DeleteIdeaForm(),
        'public_idea_form': PublicIdeaForm(),
        'modal': {
            'insert': False,
            'update': False
        },
    }

    return context

@ideas.route('/categories', methods=['GET', 'POST'])
@login_required
def categories():
    categories = list_categories()
    register_form = RegisterCategoryForm()
    context = {
        'register_form': register_form,
        'delete_form': DeleteCategoryForm(),
        'categories': categories
    }

    if register_form.validate_on_submit():
        create_category(register_form.name.data)
        flash("Categoria registrada exitosamente.", category="success")

        return redirect(url_for('ideas.categories'))        

    return render('ideas/categories.html', **context)

@ideas.route('/category/delete/<category_id>', methods=['POST'])
@login_required
def delete_category_view(category_id):
    delete_category(category_id)
    flash("Categoria eliminada", category="success")   

    return redirect(url_for('ideas.categories')) 


@ideas.route('/home', methods=['GET', 'POST'])
@login_required
def home():
    """ Método para retornar al home de la aplicación. """
    context = contextHome()
    idea_form = context["idea_form"]
    if idea_form.validate_on_submit():
        form_dict = get_dict_from_wftform(idea_form)
        form_dict['username'] = context['username']
        if idea_form.id.data == "":
            create_idea(form_dict)
            flash("Ideas creada.", category="success")
            return redirect(url_for('ideas.home'))
        else:
            update_idea_db(form_dict)
            flash("Idea actualizada correctamente !!", category="success")
            return redirect(url_for("ideas.home"))
        
    return render('ideas/home.html', **context)

@ideas.route('/insert')
@login_required
def insertideas_view():
    context = contextHome()
    context["modal"] = {
        "insert": True,
        "udpate": False
    }

    return render('ideas/home.html', **context)

@ideas.route('/delete_idea/<idea_id>', methods=['POST'])
@login_required
def delete_idea(idea_id):
    delete_idea_db(idea_id)
    flash("Idea eliminada exitosamente", category="success")
    
    return redirect(url_for("ideas.home"))

@ideas.route('/public_idea/<idea_id>/<int:is_public>', methods=['POST'])
@login_required
def public_idea(idea_id, is_public):
    update_state_idea_db(idea_id, is_public)
    flash("Idea actualizada exitosamente !!", category="success")

    return redirect(url_for("ideas.home"))

@ideas.route('/update_idea/<idea_id>', methods=['POST'])
@login_required
def update_idea(idea_id):
    context = contextHome()
    idea_form = context["idea_form"]

    idea = get_idea_by_id(idea_id)
    idea_form.id.data = idea.id
    idea_form.title.data = idea.title
    idea_form.description.data = idea.description
    idea_form.is_public.data = idea.is_public
    idea_form.category_id.data = idea.category_id

    context["idea_form"] = idea_form
    context["modal"] = {
        'insert': False,
        'update': True
    }

    return render('ideas/home.html', **context)

app/ideas/templates/ideas/categories.html
{% extends 'base.html' %}
{% import 'bootstrap/wtf.html' as wtf %}
{% import 'macros/macroListCategory.html' as macroCategory %}
{% block title %}
    {{ super() }}
    categorias
{% endblock %}
{% block content %}
    <div class="container">
        <div class="row">
            <div class="col-md-4">
                <h4>Registrar categorias</h4>
                {{ wtf.quick_form(register_form, button_map={'submit': 'primary'}) }}
            </div>
            <div class="col-md-8">
                <h4>Listado de categorias</h4>
                <div class="container table-responsive">
                    <table class="table">
                        <thead>
                            <tr>
                                <th>Category</th>
                                <th>Eliminar</th>
                            </tr>
                        </thead>
                        <tbody>
                            {% for category in categories %}
                                {{ macroCategory.render_list(category, delete_form) }}
                            {% endfor %}
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

app/ideas/templates/ideas/home.html
{% extends 'base.html' %}
{% import 'macros/macroModal.html' as macro_modal %}
{% import 'macros/macroListIdeas.html' as macro_ideas %}
{% block title %}
    {{ super() }}
    Home
{% endblock %}
{% block content %}
    <div class="container">
        <a href="{{ url_for('ideas.insertideas_view') }}" class="btn btn-primary btn-lg">Idea nueva</a>
        {% if modal['insert'] is true %}
            {{ macro_modal.render_modal("Registro de ideas", idea_form, 'ideas.home', 'primary') }}
        {% endif %}
        {% if modal['update'] is true %}
            {{ macro_modal.render_modal("Actualización de ideas", idea_form, 'ideas.home', 'danger') }}
        {% endif %}
        <hr>
        <div class="table-responsive">
            <table class="table">
                <thead>
                    <tr>
                        <th>Título</th>
                        <th>Descripción</th>
                        <th>Categoria</th>
                        <th>Visibilidad</th>
                        <th>Acciones</th>
                    </tr>
                </thead>
                <tbody>
                    {% for idea in ideas %}
                        {{ macro_ideas.render_list(idea, delete_form, public_idea_form) }}
                    {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
{% endblock %}
{% block custom_scripts %}
    {% if (modal['insert'] is true) or (modal['update'] is true) %}
        <script>
            window.onload = function(){
                $("#macroModal").modal("show");
            }
        </script>
    {% endif %}
{% endblock %}

app/ideas/templates/macros/macroListCategory.html
{% import 'bootstrap/wtf.html' as wtf %}

{% macro render_list(category, delete_form) %}
    <tr>
        <td>{{ category.name}}</td>
        <td>
            <form action="{{ url_for('ideas.delete_category_view', category_id=category.id) }}", method="post">
                {{ delete_form.csrf_token }}
                <button type="submit" class="btn btn-danger">
                    <i class="fas fa-times-circle"></i>
                </button>
            </form>
        </td>
    </tr>
{% endmacro %}

app/ideas/templates/macros/macroListIdeas.html
{% macro render_list(idea, delete, public_change) %}
    <tr>
        <td>{{ idea.title }}</td>
        <td>{{ idea.description }}</td>
        <td>{{ idea.category.name }}</td>
        <td>{{ idea.is_public | visibility_public_or_private }}</td>
        <td>
            <div class="items fr-3">
                <div class="item">
                    <form action="{{ url_for('ideas.delete_idea', idea_id=idea.id)}}" method="POST">
                        {{ delete.csrf_token }}
                        <button type="submit" class=" btn btn-danger">
                            <i class="fas fa-times-circle"></i>
                        </button>
                    </form>
                </div>
                <div class="item">
                    <form action="{{ url_for('ideas.update_idea', idea_id=idea.id)}}" method="POST">
                        <button type="submit" class=" btn btn-primary">
                            <i class="fas fa-pencil-alt"></i>
                        </button>
                    </form>
                </div>
                <div class="item">
                    <form action="{{ url_for('ideas.public_idea', idea_id=idea.id, is_public=1 if idea.is_public else 0 )}}" method="POST">
                    {{ public_change.csrf_token }}
                    <button type="submit" class=" btn btn-info">
                            <i class="fas fa-eye"></i>
                        </button>
                    </form>
                </div>
            </div>
        </td>
    </tr>
{% endmacro %}